services:
  - type: web
    name: streamlit-genai-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.enableCORS false"
    envVars:
      - key: ENV
        value: production
